dinner_guests = ["Jesus Christ", "Ben Franklin", "Albert Einstein"]
print(dinner_guests[0] + ", you're invited to dinner.")
print(dinner_guests[1] + ", you're invited to dinner.")
print(dinner_guests[2] + ", you're invited to dinner.")
print("I found a bigger table")
dinner_guests.insert(0, "Paul McCartney")
dinner_guests.insert(2, "Elon Musk")
dinner_guests.append("Martin Luther King, Jr.")
print(dinner_guests[0] + ", you're invited to dinner.")
print(dinner_guests[1] + ", you're invited to dinner.")
print(dinner_guests[2] + ", you're invited to dinner.")
print(dinner_guests[3] + ", you're invited to dinner.")
print(dinner_guests[4] + ", you're invited to dinner.")
print(dinner_guests[5] + ", you're invited to dinner.")
print(len(dinner_guests))
